### ISSUE TITLE
Unexpected zip file

### ISSUE THREAD

**Issue by jonathanfishbein1** [nikita-volkov/typeclasses#1]
Hi,

I apologize, I'm running into a bug when running elm bump

    `Starting downloads...

      ✗ nikita-volkov/typeclasses 1.6.0

    -- CORRUPT ZIP -----------------------------------------------------------------

    I got an unexpected zip file from:

        <https://github.com/nikita-volkov/typeclasses/zipball/1.6.0/>

    I check the hash the zip, and it seems off:

      Expected: 2e12e7e369e860fbd8ebca680b1a84817097f4bd
        Actual: 86587a0288d499c71e8b62f975e75b879b16258d

    This usually means that the package author moved the version tag, so report it
    to them and see if that is the issue. Folks on Elm slack can probably help as
    well.`

Any ideas?

**Comment by mitchellwrosen** [comment]
@nikita-volkov I'm getting this as well when I `elm install nikita-volkov/hashing-containers`

**Comment by nikita-volkov** [comment]
Sorry, somehow missed the notification about the original issue. I've made a new release `1.6.1`, it should fix the issue.

**Comment by mitchellwrosen** [comment]
Thanks a lot.
